# Generated by Django 5.1.3 on 2024-11-20 20:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název produktu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena produktu')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Číslo pokoje')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Kapacita pokoje')),
                ('numberOfBeds', models.PositiveSmallIntegerField(verbose_name='Počet postelí')),
                ('roomType', models.CharField(choices=[('King', 'Královský'), ('Luxury', 'Luxusní'), ('Normal', 'Standardní'), ('Economic', 'Ekonomický')], max_length=20, verbose_name='Typ pokoje')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena za noc')),
                ('statusStartDate', models.DateField(blank=True, null=True, verbose_name='Začátek stavu pokoje')),
                ('statusEndDate', models.DateField(blank=True, null=True, verbose_name='Konec stavu pokoje')),
                ('name', models.CharField(max_length=100, verbose_name='Název pokoje')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis pokoje')),
                ('status', models.CharField(choices=[('Available', 'Dostupné'), ('Occupied', 'Obsazené'), ('Maintenance', 'Údržba')], default='Available', max_length=20, verbose_name='Stav pokoje')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfReservation', models.DateField(default=django.utils.timezone.now, verbose_name='Datum vytvoření rezervace')),
                ('startDate', models.DateField(verbose_name='Začátek pobytu')),
                ('endDate', models.DateField(verbose_name='Konec pobytu')),
                ('status', models.CharField(choices=[('Active', 'Aktivní'), ('Cancelled', 'Zrušeno')], default='Active', max_length=20, verbose_name='Stav rezervace')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guest', verbose_name='Host')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='Pokoj')),
            ],
        ),
        migrations.CreateModel(
            name='Dependees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno osoby')),
                ('relation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vztah k hostovi')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.booking', verbose_name='Rezervace')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Důvod refundace')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Částka refundace')),
                ('status', models.CharField(choices=[('Pending', 'Nevyřízeno'), ('Processed', 'Zpracováno')], default='Pending', max_length=20, verbose_name='Stav refundace')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guest', verbose_name='Host')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.booking', verbose_name='Rezervace')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='Obrázek pokoje')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Popisek obrázku')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='room.room', verbose_name='Pokoj')),
            ],
        ),
        migrations.CreateModel(
            name='RoomServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(default=django.utils.timezone.now, verbose_name='Datum vytvoření služby')),
                ('servicesType', models.CharField(choices=[('Food', 'Jídlo'), ('Cleaning', 'Úklid'), ('Technical', 'Technická podpora')], max_length=20, verbose_name='Typ služby')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena služby')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis služby')),
                ('curBooking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.booking', verbose_name='Rezervace')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='Pokoj')),
            ],
        ),
    ]
