# Generated by Django 5.1.3 on 2024-11-17 21:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options_alter_guest_options_and_more'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Žádný popis', max_length=100, verbose_name='Název pokoje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Číslo pokoje'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Dostupné'), ('Occupied', 'Obsazené'), ('Maintenance', 'Údržba')], default='Available', max_length=20, verbose_name='Stav pokoje'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dateOfReservation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum rezervace'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='endDate',
            field=models.DateField(verbose_name='Konec pobytu'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guest', verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='roomNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='Pokoj'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDate',
            field=models.DateField(verbose_name='Začátek pobytu'),
        ),
        migrations.AlterField(
            model_name='dependees',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.booking', verbose_name='Rezervace'),
        ),
        migrations.AlterField(
            model_name='dependees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dependees',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Jméno osoby'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guest', verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(verbose_name='Důvod refundace'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.booking', verbose_name='Rezervace'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.SmallIntegerField(verbose_name='Kapacita'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Číslo pokoje'),
        ),
        migrations.AlterField(
            model_name='room',
            name='numberOfBeds',
            field=models.SmallIntegerField(verbose_name='Počet postelí'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(verbose_name='Cena za noc'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.CharField(choices=[('King', 'King'), ('Luxury', 'Luxury'), ('Normal', 'Normal'), ('Economic', 'Economic')], max_length=20, verbose_name='Typ pokoje'),
        ),
        migrations.AlterField(
            model_name='room',
            name='statusEndDate',
            field=models.DateField(blank=True, null=True, verbose_name='Konec rezervace'),
        ),
        migrations.AlterField(
            model_name='room',
            name='statusStartDate',
            field=models.DateField(blank=True, null=True, verbose_name='Začátek rezervace'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='createdDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='curBooking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.booking', verbose_name='Rezervace'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='price',
            field=models.FloatField(verbose_name='Cena služby'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='Pokoj'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='servicesType',
            field=models.CharField(choices=[('Food', 'Food'), ('Cleaning', 'Cleaning'), ('Technical', 'Technical')], max_length=20, verbose_name='Typ služby'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='Obrázek pokoje')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Popisek obrázku')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='room.room', verbose_name='Pokoj')),
            ],
        ),
    ]
