"""
Django settings for HMS project.

Generated by 'django-admin startproject' using Django 3.1.4.

Pro více informací o tomto souboru:
https://docs.djangoproject.com/en/3.1/topics/settings/

Pro kompletní seznam nastavení:
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Cesta k základnímu adresáři projektu
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------
# Základní nastavení projektu
# ------------------------------

# Tajný klíč (v produkci by měl být uložen v proměnných prostředí)
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'replace_with_your_secret_key_for_deployment')

# Ladicí režim (v produkci musí být nastaven na False)
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

# Povolené hosty (v produkci zde budou domény nebo IP adresy serveru)
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# ------------------------------
# Aplikace a middleware
# ------------------------------

# Instalované aplikace
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Třetí strany
    'phonenumber_field',  # Pro zpracování telefonních čísel

    # Lokální aplikace
    'hotel',
    'accounts',
    'room',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Hlavní konfigurace URL
ROOT_URLCONF = 'HMS.urls'

# Nastavení šablon
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Cesta k adresáři šablon
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI aplikace (používá se při nasazení na server)
WSGI_APPLICATION = 'HMS.wsgi.application'

# ------------------------------
# Nastavení databáze
# ------------------------------

# Výchozí databáze (SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ------------------------------
# Validace hesel
# ------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Minimální délka hesla
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ------------------------------
# Nastavení přihlášení a odhlášení
# ------------------------------
LOGIN_REDIRECT_URL = '/'  # Přesměrování po přihlášení
LOGOUT_REDIRECT_URL = '/'  # Přesměrování po odhlášení

# ------------------------------
# Nastavení lokalizace
# ------------------------------
LANGUAGE_CODE = 'cs'  # Jazyk aplikace (čeština)
TIME_ZONE = 'UTC'  # Časové pásmo
USE_I18N = True  # Povolit internacionalizaci
USE_L10N = True  # Povolit lokalizaci
USE_TZ = True  # Povolit časové zóny

# ------------------------------
# Statické soubory
# ------------------------------
STATIC_URL = '/static/'  # URL cesta pro statické soubory
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Cesta k vývojovým statickým souborům
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Cesta k produkčním statickým souborům

# ------------------------------
# Média (nahrané soubory)
# ------------------------------
MEDIA_URL = '/media/'  # URL cesta pro média
MEDIA_ROOT = BASE_DIR / 'media'  # Složka pro ukládání mediálních souborů

# ------------------------------
# Nastavení e-mailu
# ------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Výchozí pro vývoj
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', 'smtp.gmail.com')  # SMTP server
EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', 587))  # Port SMTP
EMAIL_USE_TLS = True  # Použití šifrování TLS
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', 'your_email@example.com')  # E-mailový účet
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', 'your_password')  # Heslo k e-mailu

# ------------------------------
# Protokolování
# ------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',  # Logování do konzole
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'ERROR',  # Úroveň logování
    },
}