# Generated by Django 5.1.3 on 2024-11-21 13:45

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název události')),
                ('event_type', models.CharField(choices=[('Movie', 'Film'), ('Theater', 'Divadlo'), ('Conference', 'Konference'), ('Concert', 'Koncert'), ('Entertainment', 'Zábava'), ('Live Music', 'Živá hudba')], max_length=50, verbose_name='Typ události')),
                ('location', models.CharField(max_length=100, verbose_name='Místo konání')),
                ('start_date', models.DateTimeField(verbose_name='Datum začátku')),
                ('end_date', models.DateTimeField(verbose_name='Datum konce')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis události')),
            ],
            options={
                'verbose_name': 'Událost',
                'verbose_name_plural': 'Události',
            },
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název jídla')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('category', models.CharField(max_length=100, verbose_name='Kategorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
            ],
            options={
                'verbose_name': 'Položka jídelního menu',
                'verbose_name_plural': 'Jídelní menu',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Obsah reportu')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reporty',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(verbose_name='Číslo pokoje')),
                ('room_type', models.CharField(max_length=50, verbose_name='Typ pokoje')),
                ('capacity', models.IntegerField(verbose_name='Kapacita')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena za noc')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostupnost')),
            ],
            options={
                'verbose_name': 'Pokoj',
                'verbose_name_plural': 'Pokoje',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Název položky')),
                ('quantity', models.IntegerField(verbose_name='Počet kusů skladem')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Datum poslední aktualizace')),
            ],
            options={
                'verbose_name': 'Sklad',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název oznámení')),
                ('content', models.TextField(verbose_name='Obsah oznámení')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Odesílatel')),
            ],
            options={
                'verbose_name': 'Oznámení',
                'verbose_name_plural': 'Oznámení',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Telefonní číslo')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Zaměstnanec',
                'verbose_name_plural': 'Zaměstnanci',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Plné jméno')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Telefonní číslo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosté',
            },
        ),
        migrations.CreateModel(
            name='EventAttendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_dependents', models.IntegerField(default=0, verbose_name='Počet doprovodů')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.event', verbose_name='Událost')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.guest', verbose_name='Host')),
            ],
            options={
                'verbose_name': 'Účastník události',
                'verbose_name_plural': 'Účastníci událostí',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Celková částka')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum vystavení')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.guest', verbose_name='Host')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.CharField(max_length=255, verbose_name='Rezervace')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Částka')),
                ('status', models.CharField(max_length=50, verbose_name='Stav refundace')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Host')),
            ],
            options={
                'verbose_name': 'Refundace',
                'verbose_name_plural': 'Refundace',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Začátek pobytu')),
                ('end_date', models.DateField(verbose_name='Konec pobytu')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.guest', verbose_name='Host')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Pokoj')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
            },
        ),
    ]
